FROM python:3.11-slim

WORKDIR /app

COPY back/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY back/ .

RUN python seed.py ; true

CMD ["sh", "-c", "python add_admin.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
