databases:
  - name: fastit-db
    databaseName: fastit
    user: fastit
    plan: free

services:
  - type: web
    name: fastit
    runtime: python
    buildCommand: bash build.sh && pip install -r back/requirements.txt
    startCommand: cd back && bash startup.sh
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: fastit-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: "nahum.diaz@nadilop.cl"
      - key: ICECAT_USERNAME
        sync: false
      - key: CHILEXPRESS_API_KEY
        sync: false
